---
title: "NAR Figure 4 Effect of noise level"
output: html_document
date: "2023-10-11"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F)
library(dplyr)
library(ggsci)
library(scales)
library(ggplot2)
library(ggthemes)
library(magrittr)
library(tidyverse)
library(patchwork)
library(cowplot)

rm(list =ls())
# set the color for each GSA method
mypal = c("#A7CEE2","#428DBF","#F0E442","#E0271E","#EB8E47","#7A52A6","#C1A9D2")
show_col(mypal)
names(mypal) <- c("AddModuleScore","AUCell","JASMINE","scPS","SCSE","UCell","ssGSEA")
# set the theme for ggplot2
My_Theme <- theme(axis.ticks = element_blank(),
                  legend.title=element_blank(),
                  legend.position = "top", 
                  legend.direction = "vertical", 
                  legend.justification='center',
                  plot.caption = element_text(hjust = 0.5, vjust = -1, size=14),
                  panel.background = element_rect(fill = NA),
                  panel.grid.major = element_line(colour = "#e6e6e6"),
                  panel.ontop = F,
                  panel.border = element_rect(color = "#333333", fill = NA, size = 1))
```

splatter scenario 1
p.splatter.1
```{r}
# scenario 1 sample size = 200
setwd("/Users/rwang4/Library/CloudStorage/Box-Box/Ruoqiao Thakar Lab/Single-cell Pathway Score (scPS)/Data & results/SSD")
dat1 <- read.csv("Sample size 200/Scenario 1/Two side dat matrix 2.csv",header = T,row.names = 1)
Methods <- c("ssGSEA","JASMINE","AUCell","UCell","scPS","SCSE","AddModuleScore")
dat1$Methods <- rep(Methods,dim(dat1)[1]/7)
dat1$cells <- 200
dat1$Scenario <- "Scenario 1"
dat1$Noise <- rep(rep(c("0","20","50","80","100"), each=dim(dat1)[1]/50),10)

# get mean & standard deviation by method
data_msd <- dat1 %>% group_by(Methods,geneset,Noise) %>%
            summarise_at(vars(count),list(mean = mean,sd = sd)) %>% as.data.frame()

# set with gene set size = 100, cell count = 200
data_msd.2 <- data_msd[grep("GS-100-",data_msd$geneset),]
data_msd.2$Noise <-  factor(data_msd.2$Noise, levels = c("0","20","50","80","100"))
data_msd.2$Methods <- factor(data_msd.2$Methods, levels=c("AddModuleScore","AUCell","JASMINE","scPS","SCSE","UCell","ssGSEA"))

# lineplot
min(data_msd.2$mean-data_msd.2$sd)
p.splatter.1 <- ggplot(data = data_msd.2) +
  geom_line(aes(x=Noise, y=mean, linetype = Methods, group=Methods, color=Methods), size=1, alpha=0.8) +
  geom_point(aes(x=Noise, y=mean,color=Methods),size=2, alpha=0.8) +
  scale_fill_manual(values = mypal)+
  scale_color_manual(values = mypal)+
  geom_errorbar(aes(x=Noise, y=mean,ymin=mean-sd, ymax=mean+sd, color=Methods), width=0.3, size=1, alpha=0.8, position=position_dodge(0.001))+
  scale_y_continuous(breaks = c(0, 20, 40, 60, 80, 100),limits = c(-22,120))+ 
  labs(x="Noise level (%)", y = "Recovery rate (%)") +
  My_Theme +  guides(color=guide_legend(nrow=1)) 

p.splatter.1

# Recovery rate 
data_msd.2[data_msd.2$geneset=="GS-100-0-",]$sd <- round(data_msd.2[data_msd.2$geneset=="GS-100-0-",]$sd,2)
data_msd.2[data_msd.2$geneset=="GS-100-0-",]
# False Positive rate 
data_msd.2[data_msd.2$geneset=="GS-100-1-",]$sd <- round(data_msd.2[data_msd.2$geneset=="GS-100-1-",]$sd,2)
data_msd.2[data_msd.2$geneset=="GS-100-1-",]
```

splatter scenario 2
p.splatter.2
```{r}
# scenario 2 sample size = 200
setwd("/Users/rwang4/Library/CloudStorage/Box-Box/Ruoqiao Thakar Lab/Single-cell Pathway Score (scPS)/Data & results/SSD")
dat1 <- read.csv("Sample size 200/Scenario 2/Two side dat matrix 2.csv",header = T,row.names = 1)
Methods <- c("ssGSEA","JASMINE","AUCell","UCell","scPS","SCSE","AddModuleScore")
dat1$Methods <- rep(Methods,dim(dat1)[1]/7)
dat1$cells <- 200
dat1$Scenario <- "Scenario 1"
dat1$Noise <- rep(rep(c("0","20","50","80","100"), each=dim(dat1)[1]/50),10)


# get mean & standard deviation by method
data_msd <- dat1 %>% group_by(Methods,geneset,Noise) %>%
            summarise_at(vars(count),list(mean = mean,sd = sd)) %>% as.data.frame()

# set with gene set size = 100, cell count = 200
data_msd.2 <- data_msd[grep("GS-100-",data_msd$geneset),]
data_msd.2$Noise <-  factor(data_msd.2$Noise, levels = c("0","20","50","80","100"))
data_msd.2$Methods <- factor(data_msd.2$Methods, levels=c("AddModuleScore","AUCell","JASMINE","scPS","SCSE","UCell","ssGSEA"))

# lineplot
min(data_msd.2$mean-data_msd.2$sd)
p.splatter.2 <- ggplot(data = data_msd.2) +
  geom_line(aes(x=Noise, y=mean, linetype = Methods, group=Methods, color=Methods), size=1, alpha=0.8) +
  geom_point(aes(x=Noise, y=mean,color=Methods),size=2, alpha=0.8) +
  scale_fill_manual(values = mypal)+
  scale_color_manual(values = mypal)+
  geom_errorbar(aes(x=Noise, y=mean,ymin=mean-sd, ymax=mean+sd, color=Methods), width=0.3, size=1, alpha=0.8, position=position_dodge(0.001))+
  scale_y_continuous(breaks = c(0, 20, 40, 60, 80, 100),limits = c(-22,120))+ 
  labs(x="Noise level (%)", y = "Recovery rate (%)") +
  My_Theme +  guides(color=guide_legend(nrow=1)) 

p.splatter.2

# Recovery rate 
data_msd.2[data_msd.2$geneset=="GS-100-0-",]$sd <- round(data_msd.2[data_msd.2$geneset=="GS-100-0-",]$sd,2)
data_msd.2[data_msd.2$geneset=="GS-100-0-",]
# False Positive rate 
data_msd.2[data_msd.2$geneset=="GS-100-1-",]$sd <- round(data_msd.2[data_msd.2$geneset=="GS-100-1-",]$sd,2)
data_msd.2[data_msd.2$geneset=="GS-100-1-",]
```

RWSD scenario 1
p.rwsd.1
```{r}
# scenario 1 sample size = 200
setwd("/Users/rwang4/Library/CloudStorage/Box-Box/Ruoqiao Thakar Lab/Single-cell Pathway Score (scPS)/Data & results/RWSD")
dat1 <- read.csv("Sample size 200/Scenario 1/Two side dat matrix 2.csv",header = T,row.names = 1)
Methods <- c("ssGSEA","JASMINE","AUCell","UCell","scPS","SCSE","AddModuleScore")
dat1$Methods <- rep(Methods,dim(dat1)[1]/7)
dat1$cells <- 200
dat1$Scenario <- "Scenario 1"
dat1$Noise <- rep(rep(c("0","20","50","80","100"), each=dim(dat1)[1]/50),10)

# get mean & standard deviation by method
data_msd <- dat1 %>% group_by(Methods,geneset,Noise) %>%
            summarise_at(vars(count),list(mean = mean,sd = sd)) %>% as.data.frame()

# set with gene set size = 100, cell count = 200
data_msd.2 <- data_msd[grep("GS-100-",data_msd$geneset),]
data_msd.2$Noise <-  factor(data_msd.2$Noise, levels = c("0","20","50","80","100"))
data_msd.2$Methods <- factor(data_msd.2$Methods, levels=c("AddModuleScore","AUCell","JASMINE","scPS","SCSE","UCell","ssGSEA"))

# lineplot
min(data_msd.2$mean-data_msd.2$sd)
p.rwsd.1 <- ggplot(data = data_msd.2) +
  geom_line(aes(x=Noise, y=mean, linetype = Methods, group=Methods, color=Methods), size=1, alpha=0.8) +
  geom_point(aes(x=Noise, y=mean,color=Methods),size=2, alpha=0.8) +
  scale_fill_manual(values = mypal)+
  scale_color_manual(values = mypal)+
  geom_errorbar(aes(x=Noise, y=mean,ymin=mean-sd, ymax=mean+sd, color=Methods), width=0.3, size=1, alpha=0.8, position=position_dodge(0.001))+
  scale_y_continuous(breaks = c(0, 20, 40, 60, 80, 100),limits = c(-22,120))+ 
  labs(x="Noise level (%)", y = "Recovery rate (%)") +
  My_Theme +  guides(color=guide_legend(nrow=1)) 

p.rwsd.1

# Recovery rate 
data_msd.2[data_msd.2$geneset=="GS-100-0-",]$sd <- round(data_msd.2[data_msd.2$geneset=="GS-100-0-",]$sd,2)
data_msd.2[data_msd.2$geneset=="GS-100-0-",]
# False Positive rate 
data_msd.2[data_msd.2$geneset=="GS-100-1-",]$sd <- round(data_msd.2[data_msd.2$geneset=="GS-100-1-",]$sd,2)
data_msd.2[data_msd.2$geneset=="GS-100-1-",]
```

RWSD scenario 2
p.rwsd.2
```{r}
# scenario 1 sample size = 200
setwd("/Users/rwang4/Library/CloudStorage/Box-Box/Ruoqiao Thakar Lab/Single-cell Pathway Score (scPS)/Data & results/RWSD")
dat1 <- read.csv("Sample size 200/Scenario 2/Two side dat matrix 2.csv",header = T,row.names = 1)
Methods <- c("ssGSEA","JASMINE","AUCell","UCell","scPS","SCSE","AddModuleScore")
dat1$Methods <- rep(Methods,dim(dat1)[1]/7)
dat1$cells <- 200
dat1$Scenario <- "Scenario 1"
dat1$Noise <- rep(rep(c("0","20","50","80","100"), each=dim(dat1)[1]/50),10)


# get mean & standard deviation by method
data_msd <- dat1 %>% group_by(Methods,geneset,Noise) %>%
            summarise_at(vars(count),list(mean = mean,sd = sd)) %>% as.data.frame()

# set with gene set size = 100, cell count = 200
data_msd.2 <- data_msd[grep("GS-100-",data_msd$geneset),]
data_msd.2$Noise <-  factor(data_msd.2$Noise, levels = c("0","20","50","80","100"))
data_msd.2$Methods <- factor(data_msd.2$Methods, levels=c("AddModuleScore","AUCell","JASMINE","scPS","SCSE","UCell","ssGSEA"))

# lineplot
min(data_msd.2$mean-data_msd.2$sd)
p.rwsd.2 <- ggplot(data = data_msd.2) +
  geom_line(aes(x=Noise, y=mean, linetype = Methods, group=Methods, color=Methods), size=1, alpha=0.8) +
  geom_point(aes(x=Noise, y=mean,color=Methods),size=2, alpha=0.8) +
  scale_fill_manual(values = mypal)+
  scale_color_manual(values = mypal)+
  geom_errorbar(aes(x=Noise, y=mean,ymin=mean-sd, ymax=mean+sd, color=Methods), width=0.3, size=1, alpha=0.8, position=position_dodge(0.001))+
  scale_y_continuous(breaks = c(0, 20, 40, 60, 80, 100),limits = c(-22,120))+ 
  labs(x="Noise level (%)", y = "Recovery rate (%)") +
  My_Theme +  guides(color=guide_legend(nrow=1)) 

p.rwsd.2

# Recovery rate 
data_msd.2[data_msd.2$geneset=="GS-100-0-",]$sd <- round(data_msd.2[data_msd.2$geneset=="GS-100-0-",]$sd,2)
data_msd.2[data_msd.2$geneset=="GS-100-0-",]
# False Positive rate 
data_msd.2[data_msd.2$geneset=="GS-100-1-",]$sd <- round(data_msd.2[data_msd.2$geneset=="GS-100-1-",]$sd,2)
data_msd.2[data_msd.2$geneset=="GS-100-1-",]

```

plot for scenario 1 and 2
```{r}
library(ggpubr)
p <- ggarrange(p.splatter.1, p.splatter.2, 
          p.rwsd.1, p.rwsd.2,
          nrow =2,
          ncol =2,
          align='h', 
          labels=c('A', 'B','C','D'),
          common.legend = T)

p
pdf('/Users/rwang4/Desktop/Effect of Noise level.pdf', width = 10, height = 8)
p
dev.off()
```

splatter scenario 1 without signal
p.splatter.1.wo
```{r}
setwd("/Users/rwang4/Library/CloudStorage/Box-Box/Ruoqiao Thakar Lab/Single-cell Pathway Score (scPS)/Data & results/SSD/")
# scenario 1 sample size = 200
dat1 <- read.csv("Sample size 200/Scenario 1 without signal/Two side dat matrix 2.csv",header = T,row.names = 1)
Methods <- c("ssGSEA","JASMINE","AUCell","UCell","scPS","SCSE","AddModuleScore")
dat1$Methods <- rep(Methods,dim(dat1)[1]/7)
dat1$cells <- 200
dat1$Scenario <- "Scenario 1 without signal"
dat1$Noise <- rep(rep(c("0","20","50","80","100"), each=dim(dat1)[1]/50),10)

# get mean & standard deviation by method
data_msd <- dat1 %>% group_by(Methods,geneset,Noise) %>%
            summarise_at(vars(count),list(mean = mean,sd = sd)) %>% as.data.frame()

# set with gene set size = 100, cell count = 200
data_msd.2 <- data_msd[grep("GS-100-",data_msd$geneset),]
data_msd.2$Noise <-  factor(data_msd.2$Noise, levels = c("0","20","50","80","100"))

# lineplot
min(data_msd.2$mean-data_msd.2$sd)
p.splatter.1.wo <- ggplot(data = data_msd.2) +
  geom_line(aes(x=Noise, y=mean, linetype = Methods, group=Methods, color=Methods), size=1, alpha=0.8) +
  geom_point(aes(x=Noise, y=mean,color=Methods),size=2, alpha=0.8) +
  scale_fill_manual(values = mypal)+
  scale_color_manual(values = mypal)+
  geom_errorbar(aes(x=Noise, y=mean,ymin=mean-sd, ymax=mean+sd, color=Methods), width=0.3, size=1, alpha=0.8, position=position_dodge(0.001))+
  scale_y_continuous(breaks = c(0, 20, 40, 60, 80, 100),limits = c(-22,120))+ 
  labs(x="Noise level (%)", y = "Recovery rate (%)") +
  My_Theme +  guides(color=guide_legend(nrow=1)) 

p.splatter.1.wo

sum <- data_msd.2[grep("GS-100-0-",data_msd.2$geneset),]
sum$Data <- "SSD"
sum$Scenario <- "Scenario 1 without signal"
```

splatter scenario 2 without signal
p.splatter.2.wo
```{r}
setwd("/Users/rwang4/Library/CloudStorage/Box-Box/Ruoqiao Thakar Lab/Single-cell Pathway Score (scPS)/Data & results/SSD/")
dat1 <- read.csv("Sample size 200/Scenario 2 without signal/Two side dat matrix 2.csv",header = T,row.names = 1)
Methods <- c("ssGSEA","JASMINE","AUCell","UCell","scPS","SCSE","AddModuleScore")
dat1$Methods <- rep(Methods,dim(dat1)[1]/7)
dat1$cells <- 200
dat1$Scenario <- "Scenario 2 without signal"
dat1$Noise <- rep(rep(c("0","20","50","80","100"), each=dim(dat1)[1]/50),10)

# get mean & standard deviation by method
data_msd <- dat1 %>% group_by(Methods,geneset,Noise) %>%
            summarise_at(vars(count),list(mean = mean,sd = sd)) %>% as.data.frame()

# set with gene set size = 100, cell count = 200
data_msd.2 <- data_msd[grep("GS-100-",data_msd$geneset),]
data_msd.2$Noise <-  factor(data_msd.2$Noise, levels = c("0","20","50","80","100"))

# lineplot
min(data_msd.2$mean-data_msd.2$sd)
p.splatter.2.wo <- ggplot(data = data_msd.2) +
  geom_line(aes(x=Noise, y=mean, linetype = Methods, group=Methods, color=Methods), size=1, alpha=0.8) +
  geom_point(aes(x=Noise, y=mean,color=Methods),size=2, alpha=0.8) +
  scale_fill_manual(values = mypal)+
  scale_color_manual(values = mypal)+
  geom_errorbar(aes(x=Noise, y=mean,ymin=mean-sd, ymax=mean+sd, color=Methods), width=0.3, size=1, alpha=0.8, position=position_dodge(0.001))+
  scale_y_continuous(breaks = c(0, 20, 40, 60, 80, 100),limits = c(-22,120))+ 
  labs(x="Noise level (%)", y = "Recovery rate (%)") +
  My_Theme +  guides(color=guide_legend(nrow=1)) 

p.splatter.2.wo
sum.temp <- data_msd.2[grep("GS-100-0-",data_msd.2$geneset),]
sum.temp$Data <- "SSD"
sum.temp$Scenario <- "Scenario 2 without signal"
sum <- rbind(sum,sum.temp)
```

RWSD scenario 1 without signal
p.rwsd.1.wo
```{r}
setwd("/Users/rwang4/Library/CloudStorage/Box-Box/Ruoqiao Thakar Lab/Single-cell Pathway Score (scPS)/Data & results/RWSD/")
dat1 <- read.csv("Sample size 200/Scenario 1 without signal/Two side dat matrix 2.csv",header = T,row.names = 1)
Methods <- c("ssGSEA","JASMINE","AUCell","UCell","scPS","SCSE","AddModuleScore")
dat1$Methods <- rep(Methods,dim(dat1)[1]/7)
dat1$cells <- 200
dat1$Scenario <- "Scenario 1 without signal"
dat1$Noise <- rep(rep(c("0","20","50","80","100"), each=dim(dat1)[1]/50),10)
# get mean & standard deviation by method
data_msd <- dat1 %>% group_by(Methods,geneset,Noise) %>%
            summarise_at(vars(count),list(mean = mean,sd = sd)) %>% as.data.frame()

# set with gene set size = 100, cell count = 200
data_msd.2 <- data_msd[grep("GS-100-",data_msd$geneset),]
data_msd.2$Noise <-  factor(data_msd.2$Noise, levels = c("0","20","50","80","100"))

# lineplot
min(data_msd.2$mean-data_msd.2$sd)
p.rwsd.1.wo <- ggplot(data = data_msd.2) +
  geom_line(aes(x=Noise, y=mean, linetype = Methods, group=Methods, color=Methods), size=1, alpha=0.8) +
  geom_point(aes(x=Noise, y=mean,color=Methods),size=2, alpha=0.8) +
  scale_fill_manual(values = mypal)+
  scale_color_manual(values = mypal)+
  geom_errorbar(aes(x=Noise, y=mean,ymin=mean-sd, ymax=mean+sd, color=Methods), width=0.3, size=1, alpha=0.8, position=position_dodge(0.001))+
  scale_y_continuous(breaks = c(0, 20, 40, 60, 80, 100),limits = c(-22,120))+ 
  labs(x="Noise level (%)", y = "Recovery rate (%)") +
  My_Theme +  guides(color=guide_legend(nrow=1)) 
p.rwsd.1.wo

sum.temp <- data_msd.2[grep("GS-100-0-",data_msd.2$geneset),]
sum.temp$Data <- "RWSD"
sum.temp$Scenario <- "Scenario 1 without signal"
sum <- rbind(sum,sum.temp)
```

RWSD scenario 2 without signal
p.rwsd.2.wo
```{r}
setwd("/Users/rwang4/Library/CloudStorage/Box-Box/Ruoqiao Thakar Lab/Single-cell Pathway Score (scPS)/Data & results/RWSD/")
# scenario 2
dat1 <- read.csv("Sample size 200/Scenario 2 without signal/Two side dat matrix 2.csv",header = T,row.names = 1)
Methods <- c("ssGSEA","JASMINE","AUCell","UCell","scPS","SCSE","AddModuleScore")
dat1$Methods <- rep(Methods,dim(dat1)[1]/7)
dat1$cells <- 200
dat1$Scenario <- "Scenario 2 without signal"
dat1$Noise <- rep(rep(c("0","20","50","80","100"), each=dim(dat1)[1]/50),10)

# get mean & standard deviation by method
data_msd <- dat1 %>% group_by(Methods,geneset,Noise) %>%
            summarise_at(vars(count),list(mean = mean,sd = sd)) %>% as.data.frame()

# set with gene set size = 100, cell count = 200
data_msd.2 <- data_msd[grep("GS-100-",data_msd$geneset),]
data_msd.2$Noise <-  factor(data_msd.2$Noise, levels = c("0","20","50","80","100"))

# lineplot
min(data_msd.2$mean-data_msd.2$sd)
p.rwsd.2.wo <-  ggplot(data = data_msd.2) +
  geom_line(aes(x=Noise, y=mean, linetype = Methods, group=Methods, color=Methods), size=1, alpha=0.8) +
  geom_point(aes(x=Noise, y=mean,color=Methods),size=2, alpha=0.8) +
  scale_fill_manual(values = mypal)+
  scale_color_manual(values = mypal)+
  geom_errorbar(aes(x=Noise, y=mean,ymin=mean-sd, ymax=mean+sd, color=Methods), width=0.3, size=1, alpha=0.8, position=position_dodge(0.001))+
  scale_y_continuous(breaks = c(0, 20, 40, 60, 80, 100),limits = c(-22,120))+ 
  labs(x="Noise level (%)", y = "Recovery rate (%)") +
  My_Theme +  guides(color=guide_legend(nrow=1)) 

p.rwsd.2.wo
sum.temp <- data_msd.2[grep("GS-100-0-",data_msd.2$geneset),]
sum.temp$Data <- "RWSD"
sum.temp$Scenario <- "Scenario 2 without signal"
sum <- rbind(sum,sum.temp)
```

plot for scenario 1 and 2 without signal
```{r}
library(ggpubr)
p <- ggarrange(p.splatter.1.wo, p.splatter.2.wo, 
          p.rwsd.1.wo, p.rwsd.2.wo,
          nrow =2,
          ncol =2,
          align='h', 
          labels=c('A', 'B','C','D'),
          common.legend = T)

p
pdf('/Users/rwang4/Desktop/Effect of Noise level wo signal.pdf', width = 10, height = 8)
p
dev.off()
```

